= Podman AI Lab
:navtitle: Home

// video::podmanai_intro_v1.mp4[width=640]

Welcome to this course on Podman AI Lab!

In this course, you will use *Podman Desktop with the AI Lab Extension* to increase your knowledge and gain capabilities in using open source AI models to provide businesses with AI driven solutions.  

 * Accomplished through hands-on practice of successfully installing Podman Desktop 
 * Adding the Podman AI Lab extension, downloading & serving AI models 
 * Using the playground to experiment & investigate the effectiveness of AI models
 * Using the recipe catalog to deploy various AI enabled applications


This course will be experienced from the perspective of a *development team* at the GizmoGobble  corporation. They have been tasked with integrating an AI powered ChatBot into multiple web interfaces. GizmoGobble's development team has no experience with the Podman AI Lab software, AI model serving, or integration of existing applications with AI technology.
// Can we add a hyperlink for GizmoGobble corporation? This way, someone who is interested to learn more about it can visit the page and get information.



== Course Objectives:


 . Use Podman Desktop to host an AI Model exploration environment 
 ** Gain a basic knowledge of the features of the Podman Desktop Application
 ** Understand and apply the components of the Podman AI Lab extension
 ** Understand Podman AI Lab from a developer's perspective

 . Deploy AI models within the playground feature
 ** Experiment with AI models to determine their capabilities

 . Use the model serving feature to simplify the integration with existing code bases
 **  Know where to locate code snippets for integrating AI models into applications

 . Deploy an AI-enabled application using pre-created templates called recipes
 **  Reverse-engineer open source code used in recipes for AI-enabled applications

 . Explain why Podman AI Lab is the entry point for customers into Red Hat's AI Ecosystem


== Prerequisites


* Basic knowledge of the Large Language Model (LLM) terminology.
* Interest in the simplest way to interact with AI models.
* Hardware with 4vCPUs, 8GB of memory, and 20-60GB of disk space for a good experience.
* MacOS, Windows, Linux Operating System with a GUI or Desktop enabled.



== Workshop Environment for Red Hat Associates

Red Hat associates can use the Red Hat® Demo Platform to provision a Podman Desktop environment.

Use the https://demo.redhat.com/catalog?search=podman&item=babylon-catalog-prod%2Fsandboxes-gpte.rhel-podman-desktop.prod[Getting Started with Podman Desktop,window=_blank] catalog item from Red Hat Demo Platform (RHDP).

[NOTE]
The Workshop deploys an AWS instance with the RHEL 9.4 desktop operating system installed.  The lastest version of Podman Desktop can be access through the activities menu. You will need to install the AI lab extension.  While playground, services, and model catalog environments function well; performance is limited for recipe catalog applications. 


When ordering this demo item:

* Select `Practice/Enablement` for the `Activity` field, and `Learning about the product` for the `Purpose`.

* If you have a Salesforce ID for a customer sales opportunity, then copy it to the `Salesforce ID` field. Otherwise, leave the field blank.

* In the `Region` field, select the region closest to your geographic area.

* Review the auto-stop and auto-destroy timers. You can change these later after classroom provisioning by opening a ticket with the RHDP team.




