= Podman AI Lab
:navtitle: Home

video::podmanai_intro_v1.mp4[width=640]

Welcome to this course on Podman AI Lab!

In this course, you will use *Podman Desktop with the AI Lab Extension* to increase your knowledge and gain capabilities in using open source AI Models to provide businesses with AI driven solutions.  Accomplished through hands-on practice of successfully installing Podman Desktop, adding the Podman AI Lab extension, downloading & serving AI models, using the playground to experiment & investigate the effectiveness of AI Models, and using the recipe catalog to deploy various AI enabled applications.


This course will be experienced from the perspective of a *development team* at the GizmoGobble  corporation. They have been tasked with integrating an AI powered Chatbot into multiple web interfaces. GizmoGobble's development team has no experience with the Podman AI Lab software, AI Model serving, or integration of existing applications with AI technology.
// Can we add a hyperlink for GizmoGobble corporation? This way, someone who is interested to learn more about it can visit the page and get information.


This course will guide you through the developers' journey as they install Podman Desktop, add the Podman AI Lab extension, download & serve AI models, use the *playground* to experiment with & investigate the effectiveness of AI Models, and finally use the *recipe catalog* to deploy various AI enabled applications. 


== Course Objectives:


 . Use Podman Desktop to host a AI Model exploration environment 
 ** Gain a basic knowledge of the features of the Podman Desktop Application
 ** Understand and apply the components of the Podman AI Lab extension
 ** Understand Podman AI Lab from a developer's perspective

 . Deploy AI Models within the playground feature
 ** Experiment with AI Models to determine their capabilities

 . Use the model serving feature to simplify the integration with existing code bases
 **  Know where to locate code snippets for integrating AI models into applications

 . Deploy an AI-enabled application using pre-created templates called recipes.
 **  Reverse-engineer open-source code used in recipes for AI-enabled applications

 . Explain why Podman AI Lab is the entry point for customers into Red Hat's AI Ecosystem


== Prerequisites


* Basic knowledge of the large language model terminology.
* Interest in the simplest way to interact with AI Models.
* Hardware with 4vCPUs, 8GB of memory, and 20-60GB of disk space for a good experience.
* MacOS, Windows, Linux Operating System with a GUI or Desktop enabled.



== Workshop Environment for Red Hat Associates

Red Hat associates can use the Red Hat Demo Platform to provision a Podman Desktop environment.

Use the https://demo.redhat.com/catalog?search=podman&item=babylon-catalog-prod%2Fsandboxes-gpte.rhel-podman-desktop.prod[Getting Started with Podman Desktop] catalog item from Red Hat Demo Platform (RHDP).

[NOTE]
This lab was recently updated to the version 1.1.1 of Podman Desktop, which is the version used in this course. However, the workshop runs on RHEL 9, while the lessons in this course describe using Podman AI Lab installed on MacOs.  I plan to release a video providing instructions specific to this workshop ASAP.


When ordering this demo item:

* Select `Practice/Enablement` for the `Activity` field, and `Learning about the product` for the `Purpose`.

* If you have a Salesforce ID for a customer sales opportunity, then copy it to the `Salesforce ID` field. Otherwise, leave the field blank.

* In the `Region` field, select the region closest to your geographic area.

* Review the auto-stop and auto-destroy timers. You can change these later after classroom provisioning by opening a ticket with the RHDP team.




