= Podman AI Lab
:navtitle: Home

== Introduction


In this course, through the use of Podman Desktop with the AI Lab Extension: students will  experiment with open-source AI models, interacting with integration code examples, and deploying multiple types of AI powered applications using standard laptop / desktop hardware.

In this course you will treat AI Model containerization, Model serving, Model inference, and templatized AI Application deployment as a Black Box, handled completely by the Podman application.   

No knowledge of these topics is required, you simply need to to select components from GUI - graphical user interface and let Podman Desktop handle the rest.

This course will be experienced from the perspective of an *Application Developer* who works for the ABC corporation. They have been tasked with integrating an AI powered Chatbot into multiple web interfaces. Our developer will have no experience with: the Podman Desktop application, AI Models or understanding of their operation.

This course will progress with the developer through installing Podman Desktop, adding the Podman AI Lab extension, downloading & serving an AI models, using the playground to experiment & investigate the models knowledge, and finally use *recipe* templates to deploy an AI enabled application or two. 


== Course Objectives:

As a result of taking this course, you will gain an understanding of the role of the developer in enabling AI backed applications. 

You will gain the ability to:

 . Use podman desktop to create a container runtime environment to host an AI model, 
 ** Technical overview of Podman Desktop Application
 ** Understand the components of Podman AI Lab extension
 ** Understand Podman AI Lab from a developer perspective

 . Utilize the playground feature to interact with various AI Models 
 ** Experiement with AI Models to determine their capabilities


 . Use code samples to simplify integration with existing code bases
 **  Know where to locate code snippets to connect to these AI models  

 . Deploy an AI enabled application using pre-create templates called recipes.
 **  Reverse engineer open source code used in recipes for AI enabled applications



== Prerequisites

* Basic knowledge of large language model terminology
* Interest the simplest way to interact with AI Models
* Hardware with 4vCPUs, 8GB of memory, 20~60GB of disk space; for a good experience.
* MacOS, Windows, Linux Operating System with a GUI or Desktop enabled.


== Optional: Workshop Environment for Red Hat Associates

Red Hat associates can use the Red Hat Demo Platform to provision Podman Desktop Workshop

Use the https://demo.redhat.com/catalog?search=podman&item=babylon-catalog-prod%2Fsandboxes-gpte.rhel-podman-desktop.prod[Getting Started with Podman Desktop] catalog item from Red Hat Demo Platform (RHDP).

When ordering this demo item:

* Select `Practice/Enablement` for the `Activity` field, and `Learning about the product` for the `Purpose`.

* If you have a Salesforce ID for a customer sales opportunity, then copy it to the `Salesforce ID` field. Otherwise, leave the field blank

* In the `Region` field, select the region closest to your Geographic area.

* Review the auto-stop and auto-destroy timers. You can change this later after classroom provisioning by opening a ticket with the RHDP team.


