= Podman Desktop Roadmap


Thank you for the taking the time to complete this PodMan AI Lab course.

Before you go, I wanted to share the upcoming features of Podman AI Lab in the official roadmap.


== Roadmap for AI Lab Extention

https://github.com/containers/podman-desktop-extension-ai-lab[Official Podman Desktop extention AI Lab repository with Roadmap]

The roadmap is always open and we are looking for your feedback. Please create new issues and upvote on the issues that are feeling the most important for you.

We will be working on the following items:

 * Expanded Recipes: Discover new use cases and samples to inspire and accelerate your applications.
 * GPU Acceleration: Speeding up processing times by leveraging GPU acceleration.
 * API/CLI: Interact with Podman AI Lab from CLI and APIs.
 * Enhanced Playgrounds: Streamlined workflows and UX giving a better space to experiment with LLMs and quickly iterate.
 * Fine Tuning with InstructLab: Re-train LLMs with a set of taxonomy knowledge. Learn more about the InstructLab project.
 * Enable Function Calling: Use LLMs to retrieve or interact with external tools by doing API calls.
 * Local RAG: Explore RAG pattern, load your document and test behavior of the model.
 * Bridge with AI Platforms (incl. K8s): Connect to remote models and ease deployment of applications.
