= Podman AI Lab

== What is Podman AI Lab

Podman AI Lab is an open-source tool that enables users to work with large language models (LLMs) on a local environment, simplifying the process of getting started with AI powered applications in their projects.

Podman AI Lab is designed to work seamlessly with Podman Desktop, allowing developers to leverage the power of LLMs without needing to rely on external infrastructure.

It offers resources and guidance for beginners, making it easy to explore AI and its potential.
Users can experiment with various models and prompts to find the best fit for their needs, thanks to the model experimentation capability.

Podman AI Lab simplifies the process of deploying and managing AI models in a production-like environment, making model serving accessible to all.

The extension provides interactive environments for users to try out and test various AI applications, such as chatbots, natural language processing, and computer vision tasks, through playgrounds for common use cases.

The extension can be installed quickly and easily on macOS, Windows, and Linux systems using the Podman Desktop interface.


== Primary Features of Podman AI Labs

=== Recipes Catalog

Podman AI Lab ships with a so-called Recipes Catalog that helps you navigate a number of core AI use cases and problem domains such as Chat Bots, Code Generators and Text Summarizers. Each recipe comes with detailed explanations and sample applications that can be run with various large language models (LLMs). Experimenting with multiple models allows finding the optimal one for your use case.

 * *Chatbots* that simulate human conversation, using AI to comprehend user inquiries and offer suitable responses. These capabilities are often used to augment applications that provide self-service customer support or virtual personal assistance.
 * *Text summarizers* which provide versatile capabilities across many applications and industries, where they can deliver effective and efficient information management. Using this recipe, developers can build applications to assist with things like content creation and curation, research, news aggregation, social media monitoring, and language learning.
 * *Code generators* which empower developers to concentrate on higher-level design and problem-solving by automating repetitive tasks like project setup and API integration, or to produce code templates.
 * *Object detection* helps identify and locate objects within digital images or video frames. It is a fundamental component in various applications, including autonomous vehicles, retail inventory management, precision agriculture, and sports broadcasting.
 * *Audio-to-text* transcription involves the process of automatically transcribing spoken language into written text, facilitating documentation, accessibility, and analysis of audio content.

=== AI Models Catalog

The models catalog is a curated list of Open Source models with the Apache 2.0 license. Once downloaded, the models are available to be used for AI applications, model services and playgrounds. The catalog will also users to import custom AI model and store them. 

=== Model Services

A model service offers a configurable endpoint via an OpenAI-compatible web server, facilitating a seamless integration of AI capabilities into existing applications. Upon initialization, effortlessly access detailed service information and generate code snippets in multiple programming languages to ease application integration.

The Services page allows for accessing running model services and provides further details and code snippets to interact with them.

=== Playgrounds

Podman AI Lab includes a playground environment that allows users to interact with AI models and observe their behavior. Once started, each playground ships with a generic chat client to interact with the model service. A customizable system prompt & paraemter modifcation settings widget helps in exploring the capabilities and accuracy of various models and aids in finding the best model with the best settings for the task.



== AI & Large Language Model supported format

=== GGUF Format:

Podman AI Lab supports large language models in the .gguf format and the ability to download or import these quantized, .gguf model files, and run them locally on a laptop, desktop, or equivilant virtual machine. 

GPT-Generated Unified Format (GGUF) is a file format that streamlines the use and deployment of large language models (LLMs). GGUF is specially designed to store inference models and perform well on consumer-grade computer hardware.


https://github.com/containers/ai-lab-recipes/tree/main/convert_models[ai-lab-recipes github respository] provides a tool to quickly and easily convert and quantize a model from huggingface into the *.gguf format for use with Podman AI Lab. 


=== HuggingFace _ 

https://huggingface.co/[The Hugging Face Hub] is a platform with over 350k models, 75k datasets, and 150k demo apps (Spaces), all open source and publicly available, in an online platform where people can easily collaborate and build ML together.


